### PR TITLE
fix: exit error code on arg parse failure

### LINKED ISSUE #108: Failure to parse exit command args should return 2 exit code
Just found this comment in Dax (written by someone else, not me):

https://github.com/dsherret/dax/blob/c885ba58ba52035a6cf99629dbcac90209a94604/src/commands/exit.ts#L13

This line should be changed to 2 it seems:

https://github.com/denoland/deno_task_shell/blob/26ef38332e0156136bd7bd48571753f715c18204/src/shell/commands/exit.rs#L26

### PR DESCRIPTION
**Pull request by dsherret**
Closes #108

### CODE REVIEW

File: src/shell/commands/exit.rs [hunk 1]
```diff
@@ -21,9 +21,9 @@ impl ShellCommand for ExitCommand {
     let result = match execute_exit(context.args) {
       Ok(code) => ExecuteResult::Exit(code, Vec::new()),
       Err(err) => {
-        // even if parsing args fails `exit` always exits
+        // exit exits with exit code 2 on argument parse failure
```
Comment (dsherret) [inline src/shell/commands/exit.rs:24]: It seems the exact error code to use is not dictated, but generally exit codes for error parsing is 2.

**Review by bartlomieju — APPROVED** [review]
