### PR TITLE
fix: handle quoted text beside unquoted text

### LINKED ISSUE #66: Text after quote is not parsed correctly
```
mkdir 'a/b'/c
# or even
mkdir 'a/b'c
```

```
Task test mkdir 'a/b'/c
error: Error parsing script 'test'.

Caused by:
    Unexpected character.
      /c
      ~
```

### PR DESCRIPTION
**Pull request by dsherret**
Closes #66

### CODE REVIEW

File: src/shell/mod.rs [hunk 1]
```diff
@@ -774,103 +770,106 @@ fn resolve_command_path(
...
+    if !current_text.is_empty() {
+      result.push(current_text);
+    }
+    result
   }
-  if !current_text.is_empty() {
-    result.push(current_text);
-  }
-  result
+  .boxed()
```
Comment (bartlomieju) [inline src/shell/mod.rs:872]: Shouldn't it be `boxed_local()`?

**Review by bartlomieju — APPROVED** [review]
LGTM

File: src/shell/mod.rs (hunk 1 above)
Comment (dsherret) [reply src/shell/mod.rs:872]: Yup, it would just cause a refactor of some other code (which I just did and will push soon). This was from back when I didn't understand .boxed() vs boxed_local().
