### PR TITLE
fix: do not propogate env changes outside subshells

### LINKED ISSUE #119: Parenthesised commands do not reset cwd at the end
```
(cd ./examples && deno eval -p 'Deno.cwd()') && deno eval -p 'Deno.cwd()'
```

*`deno task`*

```
/Users/lucacasonato/projects/github.com/lucacasonato/demo/examples
/Users/lucacasonato/projects/github.com/lucacasonato/demo/examples
```

*`bash`*

```
/Users/lucacasonato/projects/github.com/lucacasonato/demo/examples
/Users/lucacasonato/projects/github.com/lucacasonato/demo
```

Ref https://github.com/denoland/deno/issues/24217

### PR DESCRIPTION
**Pull request by dsherret**
Closes #119

### CODE REVIEW

File: src/shell/execute.rs [hunk 1]
```diff
@@ -589,12 +589,15 @@ async fn execute_subshell(
...
   match result {
     ExecuteResult::Exit(code, handles) => {
+      // sub shells do not cause an exit
+      ExecuteResult::Continue(code, Vec::new(), handles)
+    }
+    ExecuteResult::Continue(code, _env_changes, handles) => {
+      // env changes are not propagated
       ExecuteResult::Continue(code, Vec::new(), handles)
     }
-    ExecuteResult::Continue(_, _, _) => result,
```
Comment (dsherret) [inline src/shell/execute.rs:597]: I just went to go fix this in dax and interestingly this was impelmented correctly there, but not here.

**Review by lucacasonato — APPROVED** [review]
LGTM, thx!
